# -*- coding: utf-8 -*-
"""University World Rankings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VrtdB5YOp8zkIDjQlM3gPJT37VdMGGot

# **LANGKAH 1 : BACA DATASATE**

# 1.  Baca dataset dari file CSV menggunakan library google colab
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

"""# 2.  Tampilkan beberapa baris pertama data untuk melihat struktur dan kontennya

"""

df = pd.read_csv('cwurData.csv')
df.head()

"""# **LANGKAH 2 : MEMAHAMI DATA**

# 1.   Identifikasi jumlah baris dan kolom
"""

# Menampilkan jumlah baris dan kolom
print('Jumlah baris:', df.shape[0])
print('Jumlah kolom:', df.shape[1])

"""# 2.   Periksa tipe data pada setiap kolom"""

# Menampilkan tipe data pada setiap kolom
print('Tipe data pada setiap kolom:')
print(df.dtypes)

"""# 3.   Identifikasi dan tangani jika ada data yang hilang atau tidak valid."""

# Menampilkan jumlah data yang hilang pada setiap kolom
print('Jumlah data yang hilang pada setiap kolom:')
print(df.isnull().sum())

#hapus baris yang mempunyai data tidak valid
df.dropna(inplace=True)
#hapus kolom yang mempunyai data tidak valid
df.dropna(axis=1, inplace=True)

"""# **LANGKAH 3 : ANALISIS DATA**

# 1. Hitung total data untuk setiap produk
"""

# Hitung total data untuk setiap universitas
total_universitas = df.groupby('institution').sum()
print('Total data untuk setiap produk:')
print(total_universitas)

"""# 2. Hitung total data per bulan/tahun"""

# Hitung total data per tahun
df['tahun'] = pd.to_datetime(df['year']).dt.year
total_tahun = df.groupby('year').size()
print('Total data per tahun')
print(total_tahun)

"""# 3. Hitung rata-rata data"""

# Hitung rata-rata data
rata_rata = df.mean()
print('Rata-rata data:')
print(rata_rata)

"""# 4. Temukan produk dengan harga tertinggi dan terendah"""

# Temukan produk dengan score tertinggi dan terendah
score_tertinggi = df.loc[df['score'].idxmax()]
score_terendah = df.loc[df['score'].idxmin()]
print('Universitas dengan score tertinggi:')
print(score_tertinggi)
print('Universitas dengan score terendah:')
print(score_terendah)

"""# 5. Temukan bulan dengan total data tertinggi dan terendah."""

# Temukan tahun dengan total data tertinggi dan terendah
tahun_tertinggi = total_tahun.idxmax()
tahun_terendah = total_tahun.idxmin()
print('Tahun dengan total data tertinggi:', tahun_tertinggi)
print('Tahun dengan total data terendah:', tahun_terendah)

"""# **LANGKAH 4 : VISUALISASI DATA**

# 1.   Buat visualisasi yang relevan untuk mendukung analisis data, seperti diagram batang atau diagram garis.
"""

#diagram pie jumlah data berdasarkan negara
fig, axes = plt.subplots(1, 1, figsize = (20,12))
df['country'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title('Diagram Pie Jumlah Data Berdasarkan Negara')
plt.axis('equal')
plt.show()

# diagram histogram untuk menampilkan count dari semua kolom
fig, axes = plt.subplots(4,3, figsize=(20,15))

sns.histplot(data=df, x="world_rank", ax=axes[0,0], color='red')
sns.histplot(data=df, x="national_rank", ax=axes[0,1], color='red')
sns.histplot(data=df, x="quality_of_education", ax=axes[0,2], color='red')
sns.histplot(data=df, x="alumni_employment", ax=axes[1,0], color='red')
sns.histplot(data=df, x="quality_of_faculty", ax=axes[1,1], color='red')
sns.histplot(data=df, x="publications", ax=axes[1,2], color='red')
sns.histplot(data=df, x="influence", ax=axes[2,0], color='red')
sns.histplot(data=df, x="citations", ax=axes[2,1], color='red')
sns.histplot(data=df, x="broad_impact", ax=axes[2,2], color='red')
sns.histplot(data=df, x="patents", ax=axes[3,0], color='red')
sns.histplot(data=df, x="score", ax=axes[3,1], color='red')
sns.histplot(data=df, x="year", ax=axes[3,2], color='red')

plt.show()

"""# KESIMPULAN

Dari hasil analisis data yang telah dilakukan pada Dataset University World Rankings dapat disimpulkan bahwa terdapat beberapa kolom dalam data yaitu world_rank,	institution,	country,	national_rank,	quality_of_education,	alumni_employment,	quality_of_faculty, publications,	influence	citations,	broad_impact, dan	patents	score	year. Dalam Dataset University World Rankings terdapat baris berjumlah 2200 dan kolom berjumlah 14, yang berarti terdapat data sebanyak 2200 terdiri dari daftar world rank dalam kurun waktu tahun 2012-2015. Tipe data dalam dataset terdiri dari int64, object, dan float. Terdapat juga data yang tidak valid/hilang pada kolom broad_impact yaitu sebnyak 200 data.

Harvad University dari USA menempati world rank ke-1 dengan score 100, sedangkan Mines ParisTech dari France menempati world_rank ke-100 dengan score  43.36. Sementara itu data yang terkumpul dengan total data tertinggi yaitu pada tahun 2014 sedangkan data dengan total terendah pada tahun 2012.

Pemeringkatan universitas adalah praktik yang sulit, politis, dan kontroversial. Ada ratusan sistem pemeringkatan universitas nasional dan internasional yang berbeda-beda, banyak di antaranya berbeda pendapat satu sama lain. Pada dataset kali ini menggunakan beberapa kiteria yang kemudian diakumulasikan ke dalam score. Harvard University dari USA menjadi pemegang peringkat pertama sebagai universitas terbaik di dunia, bahkan sebanyak 26% dari data yang terkumpul USA menyumbang universitas yang masuk ke pemeringkatan dunia terbanyak, disusul oleh China, Jepang, United Kingdom, dan German.
"""